services:
  # docker-compose run --service-ports --rm app yarn add express
  # docker-compose run --service-ports --rm app yarn app.js
  app:
    image: node:alpine
    volumes:
      - .:/src/app
    working_dir: /src/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=(Host(`localhost`))"
      - "traefik.http.routers.app.entrypoints=web-80"
      - "traefik.http.routers.app.service=app"
      - "traefik.http.services.app.loadbalancer.server.port=3000"

networks:
  default:
    external: true
    name: docker_dev_net